services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      spring.datasource.url: jdbc:postgresql://postgres-db:5432/tms_db
      spring.datasource.username: tms_user
      spring.datasource.password: tms_password
    networks:
      - tms-network
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: tms_user
      POSTGRES_PASSWORD: tms_password
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - tms-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tms_user -d tms_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - tms-network
    depends_on:
      - postgres-db

networks:
  tms-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
