package com.example.tms.entity.enums;

public enum NotificationType {
    SESSION_FINANCIAL_EDIT,
    PAYOUT_GENERATED,
    PAYOUT_UPDATED,
    PAYOUT_PAID,
    INVOICE_PAID,
    CLASS_APPLICATION_APPROVED,
    CLASS_APPLICATION_REJECTED,
    TUTOR_INVITATION_ACCEPTED,
    TUTOR_ROLE_REVOKED
}
